packages:
  - "apps/*"
  - "packages/*"
  - "fixtures/*"
  - "tests"
  - "engine/crates/ve-napi"

allowBuilds:
  electron: true
  electron-builder: true
  esbuild: true
  electron-winstaller: false

onlyBuiltDependencies:
  - electron
  - electron-builder
  - esbuild
