import {
  AppWindowMac,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Bookmark,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clock3,
  Code2,
  Columns2,
  Command,
  Cookie,
  Copy,
  CornerDownLeft,
  Cpu,
  Download,
  ExternalLink,
  Eye,
  FolderOpen,
  Globe,
  Printer,
  RotateCcw,
  TextSearch,
  Unplug,
  Hand,
  Layers,
  LayoutGrid,
  ListChecks,
  Lock,
  MessageSquare,
  MessagesSquare,
  MoreHorizontal,
  PanelLeft,
  PanelLeftClose,
  PanelRight,
  Pause,
  Pencil,
  Pin,
  Play,
  Plus,
  RotateCw,
  ScanEye,
  Search,
  Settings,
  Sparkles,
  Square,
  Table2,
  Trash2,
  TriangleAlert,
  X,
  Zap,
} from "lucide-react";
import type { ReactElement } from "react";

/** One size + stroke for the whole app so every icon reads identically. */
const sz = { size: 15, strokeWidth: 1.75 } as const;
const sm = { size: 12, strokeWidth: 2 } as const;
const lg = { size: 18, strokeWidth: 1.75 } as const;

export const I = {
  back: <ArrowLeft {...sz} />,
  fwd: <ArrowRight {...sz} />,
  reload: <RotateCw {...sz} />,
  stop: <X {...sz} />,
  lock: <Lock {...sm} />,
  globe: <Globe {...sm} />,
  globeLg: <Globe {...lg} />,
  grid: <LayoutGrid {...sz} />,
  table: <Table2 {...sz} />,
  layers: <Layers {...sz} />,
  layersSm: <Layers {...sm} />,
  download: <Download {...sz} />,
  gear: <Settings {...sz} />,
  rail: <PanelRight {...sz} />,
  sidebar: <PanelLeft {...sz} />,
  sidebarClose: <PanelLeftClose {...sz} />,
  search: <Search {...sm} />,
  searchLg: <Search {...sz} />,
  chrome: <AppWindowMac {...sz} />,
  chromeSm: <AppWindowMac {...sm} />,
  clock: <Clock3 {...sz} />,
  clockSm: <Clock3 {...sm} />,
  chat: <MessageSquare {...sz} />,
  chats: <MessagesSquare {...sz} />,
  bookmark: <Bookmark {...sz} />,
  bookmarkFill: <Bookmark {...sz} fill="currentColor" />,
  sparkles: <Sparkles {...sz} />,
  sparklesSm: <Sparkles {...sm} />,
  sparklesLg: <Sparkles {...lg} />,
  engine: <Zap {...sm} />,
  cpu: <Cpu {...sm} />,
  hand: <Hand {...sz} />,
  handSm: <Hand {...sm} />,
  copy: <Copy {...sm} />,
  check: <Check {...sm} />,
  checkLg: <Check {...sz} />,
  pin: <Pin {...sm} />,
  more: <MoreHorizontal {...sz} />,
  pencil: <Pencil {...sm} />,
  trash: <Trash2 {...sm} />,
  enter: <CornerDownLeft {...sm} />,
  open: <ArrowUpRight {...sm} />,
  circle: <Circle {...sm} />,
  square: <Square {...sm} fill="currentColor" strokeWidth={0} />,
  // run controls
  play: <Play {...sm} fill="currentColor" strokeWidth={0} />,
  pause: <Pause {...sm} fill="currentColor" strokeWidth={0} />,
  close: <X {...sm} />,
  plus: <Plus {...sz} />,
  plusSm: <Plus {...sm} />,
  up: <ChevronUp {...sm} />,
  down: <ChevronDown {...sm} />,
  left: <ChevronLeft {...sm} />,
  right: <ChevronRight {...sm} />,
  send: <ArrowUp {...sz} />,
  obs: <ScanEye {...sm} />,
  eye: <Eye {...sm} />,
  run: <Play {...sm} />,
  result: <ListChecks {...sm} />,
  model: <ScanEye {...sm} />,
  downloadSm: <ArrowDownToLine {...sm} />,
  alert: <TriangleAlert {...sm} />,
  // palette command glyphs
  command: <Command {...sm} />,
  reloadSm: <RotateCw {...sm} />,
  reopen: <RotateCcw {...sm} />,
  findSm: <TextSearch {...sm} />,
  sidebarSm: <PanelLeft {...sm} />,
  sidebarCloseSm: <PanelLeftClose {...sm} />,
  bookmarkSm: <Bookmark {...sm} />,
  split: <Columns2 {...sm} />,
  folder: <FolderOpen {...sm} />,
  print: <Printer {...sm} />,
  code: <Code2 {...sm} />,
  cookie: <Cookie {...sm} />,
  unplug: <Unplug {...sm} />,
  external: <ExternalLink {...sm} />,
} satisfies Record<string, ReactElement>;
