import {
  AppWindowMac,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bot,
  Bookmark,
  ChevronDown,
  ChevronUp,
  Clock3,
  Download,
  Eye,
  Globe,
  LayoutGrid,
  ListChecks,
  Lock,
  MessageSquare,
  MessagesSquare,
  PanelLeft,
  PanelRight,
  Pause,
  Play,
  Plus,
  RotateCw,
  ScanEye,
  Search,
  Settings,
  Sparkles,
  Table2,
  TriangleAlert,
  X,
  Zap,
} from "lucide-react";
import type { ReactElement } from "react";

/** One size + stroke for the whole app so every icon reads identically. */
const sz = { size: 15, strokeWidth: 1.7 } as const;
const sm = { size: 12, strokeWidth: 2 } as const;

export const I = {
  back: <ArrowLeft {...sz} />,
  fwd: <ArrowRight {...sz} />,
  reload: <RotateCw {...sz} />,
  stop: <X {...sz} />,
  lock: <Lock {...sm} />,
  globe: <Globe {...sm} />,
  grid: <LayoutGrid {...sz} />,
  table: <Table2 {...sz} />,
  bolt: <Zap {...sz} />,
  download: <Download {...sz} />,
  gear: <Settings {...sz} />,
  rail: <PanelRight {...sz} />,
  sidebar: <PanelLeft {...sz} />,
  search: <Search {...sm} />,
  chrome: <AppWindowMac {...sz} />,
  clock: <Clock3 {...sz} />,
  chat: <MessageSquare {...sz} />,
  chats: <MessagesSquare {...sz} />,
  bookmark: <Bookmark {...sz} />,
  bookmarkFill: <Bookmark {...sz} fill="currentColor" />,
  // run controls
  play: <Play {...sm} fill="currentColor" strokeWidth={0} />,
  pause: <Pause {...sm} fill="currentColor" strokeWidth={0} />,
  close: <X {...sm} />,
  plus: <Plus {...sz} />,
  up: <ChevronUp {...sm} />,
  down: <ChevronDown {...sm} />,
  send: <ArrowUp {...sz} />,
  obs: <ScanEye {...sm} />,
  eye: <Eye {...sm} />,
  // timeline kinds
  run: <Bot {...sm} />,
  result: <ListChecks {...sm} />,
  model: <Sparkles {...sm} />,
  downloadSm: <ArrowDownToLine {...sm} />,
  alert: <TriangleAlert {...sm} />,
} satisfies Record<string, ReactElement>;
