//! Computing a [`ComputedStyle`] from cascaded declarations.
//!
//! [`ComputedStyle`] itself is generated by the property table in
//! [`crate::properties`]; this module adds the cascade-application logic:
//! CSS-wide keywords, custom properties, `var()` substitution, the
//! `font-size`-first ordering that relative units depend on, and the
//! post-cascade fix-ups (blockification of positioned elements, root display).

use std::rc::Rc;

use ve_core::Size;

pub use crate::properties::{ComputedStyle, ConvertContext, CustomProperties};
use crate::properties::{PropertyId, SpecifiedValue};
use crate::stylesheet::PropertyDeclaration;
use crate::values::{BorderCollapse, Display, Float, Rgba};

/// Per-element facts the cascade needs that are not in the declarations.
#[derive(Clone, Copy, Debug)]
pub struct ComputeContext<'a> {
    /// The parent's computed style (or the initial style for the root).
    pub parent: &'a ComputedStyle,
    /// Root element font size in pixels (`rem`).
    pub root_font_size: f32,
    /// Viewport size in pixels (`vw`, `vh`).
    pub viewport: Size,
    /// Whether this is the root element.
    pub is_root: bool,
}

impl ComputedStyle {
    /// Applies `declarations`, already sorted so that the *last* one wins, on
    /// top of the style inherited from `ctx.parent`.
    #[must_use]
    pub fn cascade(declarations: &[&PropertyDeclaration], ctx: &ComputeContext<'_>) -> Self {
        let mut style = Self::inherited_from(ctx.parent);

        // 1. Custom properties first: `var()` in other properties reads them.
        for decl in declarations
            .iter()
            .filter(|d| matches!(d.property, PropertyId::Custom(_)))
        {
            style.apply_custom(decl, ctx.parent);
        }
        // 2. `font-size` next: `em`, `%` line-height etc. depend on it.
        let mut convert = style.convert_context(ctx);
        for decl in declarations
            .iter()
            .filter(|d| d.property == PropertyId::FontSize)
        {
            style.apply(decl, ctx.parent, &convert);
        }
        convert.font_size = style.font_size;
        // 3. Everything else in cascade order.
        for decl in declarations.iter().filter(|d| {
            d.property != PropertyId::FontSize && !matches!(d.property, PropertyId::Custom(_))
        }) {
            style.apply(decl, ctx.parent, &convert);
        }

        style.fix_up(ctx.is_root);
        style
    }

    fn convert_context(&self, ctx: &ComputeContext<'_>) -> ConvertContext {
        ConvertContext {
            font_size: self.font_size,
            parent_font_size: ctx.parent.font_size,
            parent_font_weight: ctx.parent.font_weight,
            parent_color: ctx.parent.color,
            root_font_size: ctx.root_font_size,
            viewport: ctx.viewport,
        }
    }

    fn apply_custom(&mut self, decl: &PropertyDeclaration, parent: &Self) {
        let PropertyId::Custom(name) = &decl.property else {
            return;
        };
        match &decl.value {
            SpecifiedValue::Raw(raw) => {
                let resolved = match substitute_var(raw, &self.custom_properties, 0) {
                    Some(r) => r,
                    None => return, // invalid at computed-value time -> guaranteed-invalid
                };
                Rc::make_mut(&mut self.custom_properties).insert(name.clone(), resolved);
            }
            SpecifiedValue::Initial => {
                Rc::make_mut(&mut self.custom_properties).remove(name);
            }
            SpecifiedValue::Inherit | SpecifiedValue::Unset | SpecifiedValue::Revert => {
                match parent.custom_properties.get(name) {
                    Some(v) => {
                        Rc::make_mut(&mut self.custom_properties).insert(name.clone(), v.clone());
                    }
                    None => {
                        Rc::make_mut(&mut self.custom_properties).remove(name);
                    }
                }
            }
            _ => {}
        }
    }

    /// Applies one declaration. Invalid values (after `var()` substitution)
    /// behave as `unset`, per the custom properties specification.
    fn apply(&mut self, decl: &PropertyDeclaration, parent: &Self, ctx: &ConvertContext) {
        let prop = &decl.property;
        match &decl.value {
            SpecifiedValue::Inherit => self.inherit_field(prop, parent),
            SpecifiedValue::Initial => self.reset_field(prop),
            SpecifiedValue::Unset | SpecifiedValue::Revert => self.unset_field(prop, parent),
            SpecifiedValue::Var(raw) => {
                let substituted = substitute_var(raw, &self.custom_properties, 0)
                    .and_then(|text| prop.parse_value_str(&text));
                match substituted {
                    Some(value) if value.is_css_wide() => {
                        let resolved = PropertyDeclaration {
                            property: prop.clone(),
                            value,
                            important: decl.important,
                        };
                        self.apply(&resolved, parent, ctx);
                    }
                    Some(value) => {
                        if !self.set_field(prop, &value, ctx) {
                            self.unset_field(prop, parent);
                        }
                    }
                    None => self.unset_field(prop, parent),
                }
            }
            value => {
                self.set_field(prop, value, ctx);
            }
        }
    }

    fn unset_field(&mut self, prop: &PropertyId, parent: &Self) {
        if prop.is_inherited() {
            self.inherit_field(prop, parent);
        } else {
            self.reset_field(prop);
        }
    }

    /// Post-cascade adjustments mandated by CSS Display / Positioning /
    /// Backgrounds: blockification of out-of-flow and floated boxes, the
    /// root's display, and border widths of sides whose style paints nothing.
    fn fix_up(&mut self, is_root: bool) {
        if self.position.is_out_of_flow() {
            // Absolutely positioned boxes do not float.
            self.float = Float::None;
        }
        if self.position.is_out_of_flow() || self.float != Float::None || is_root {
            self.display = self.display.blockified();
        }
        if is_root && self.display == Display::Contents {
            self.display = Display::Block;
        }
        if self.border_top_style.is_none() {
            self.border_top_width = 0.0;
        }
        if self.border_right_style.is_none() {
            self.border_right_width = 0.0;
        }
        if self.border_bottom_style.is_none() {
            self.border_bottom_width = 0.0;
        }
        if self.border_left_style.is_none() {
            self.border_left_width = 0.0;
        }
        if self.border_collapse == BorderCollapse::Collapse {
            self.border_spacing_x = 0.0;
            self.border_spacing_y = 0.0;
        }
    }

    /// Returns `true` if the two styles differ in a way that changes layout
    /// (anything except paint-only properties).
    #[must_use]
    pub fn layout_eq(&self, other: &Self) -> bool {
        let paint_only = |s: &Self| {
            (
                s.color,
                s.background_color,
                s.border_top_color,
                s.border_right_color,
                s.border_bottom_color,
                s.border_left_color,
                s.opacity,
                s.visibility,
                s.pointer_events,
                s.text_decoration_line,
            )
        };
        let mut a = self.clone();
        let mut b = other.clone();
        // Neutralise paint-only differences before comparing.
        if paint_only(&a) != paint_only(&b) {
            a.color = b.color;
            a.background_color = b.background_color;
            a.border_top_color = b.border_top_color;
            a.border_right_color = b.border_right_color;
            a.border_bottom_color = b.border_bottom_color;
            a.border_left_color = b.border_left_color;
            a.opacity = b.opacity;
            a.visibility = b.visibility;
            a.pointer_events = b.pointer_events;
            a.text_decoration_line = b.text_decoration_line;
        }
        b.custom_properties = a.custom_properties.clone();
        a == b
    }

    /// Returns `true` if the element generates a box (`display != none`).
    #[must_use]
    pub fn is_displayed(&self) -> bool {
        self.display != Display::None
    }

    /// The colour used for text and as `currentcolor` (alias of `color`).
    #[must_use]
    pub fn current_color(&self) -> Rgba {
        self.color
    }

    /// Looks up a custom property by `--name`.
    #[must_use]
    pub fn custom_property(&self, name: &str) -> Option<&str> {
        self.custom_properties.get(name).map(String::as_str)
    }
}

/// Textually substitutes every `var(--name[, fallback])` in `raw`. Returns
/// `None` if a reference has no value and no fallback (or recursion is too
/// deep), which makes the declaration invalid at computed-value time.
pub fn substitute_var(raw: &str, custom: &CustomProperties, depth: usize) -> Option<String> {
    if depth > 16 {
        return None;
    }
    let mut out = String::with_capacity(raw.len());
    let mut rest = raw;
    while let Some(pos) = rest.find("var(") {
        out.push_str(&rest[..pos]);
        let after = &rest[pos + 4..];
        let (inner, tail) = split_balanced(after)?;
        let (name, fallback) = match inner.find(',') {
            Some(c) => (inner[..c].trim(), Some(inner[c + 1..].trim())),
            None => (inner.trim(), None),
        };
        if !name.starts_with("--") {
            return None;
        }
        match custom.get(name) {
            Some(value) => out.push_str(value),
            None => out.push_str(&substitute_var(fallback?, custom, depth + 1)?),
        }
        rest = tail;
    }
    out.push_str(rest);
    Some(out)
}

/// Splits `text` at the parenthesis that closes an already-opened `(`.
/// Returns the content before it and the text after it.
fn split_balanced(text: &str) -> Option<(&str, &str)> {
    let mut depth = 1usize;
    for (i, ch) in text.char_indices() {
        match ch {
            '(' => depth += 1,
            ')' => {
                depth -= 1;
                if depth == 0 {
                    return Some((&text[..i], &text[i + 1..]));
                }
            }
            _ => {}
        }
    }
    None
}

impl ComputedStyle {
    /// Serialises a longhand (or custom property) as CSS text for
    /// `getComputedStyle`. Unknown names yield the empty string.
    #[must_use]
    pub fn property_css(&self, name: &str) -> String {
        use crate::values::{LengthPercentage, LengthPercentageAuto, MaxSize};

        fn px(v: f32) -> String {
            if v == 0.0 {
                "0px".into()
            } else {
                format!("{v}px")
            }
        }
        fn lp(v: LengthPercentage) -> String {
            match v {
                LengthPercentage::Px(v) => px(v),
                LengthPercentage::Percent(p) => format!("{p}%"),
                LengthPercentage::Calc { px, percent } => format!("calc({px}px + {percent}%)"),
            }
        }
        fn lpa(v: LengthPercentageAuto) -> String {
            match v {
                LengthPercentageAuto::Auto => "auto".into(),
                LengthPercentageAuto::Px(v) => px(v),
                LengthPercentageAuto::Percent(p) => format!("{p}%"),
                LengthPercentageAuto::Calc { px, percent } => format!("calc({px}px + {percent}%)"),
            }
        }
        fn max_size(v: MaxSize) -> String {
            match v {
                MaxSize::None => "none".into(),
                MaxSize::Px(v) => px(v),
                MaxSize::Percent(p) => format!("{p}%"),
                MaxSize::Calc { px, percent } => format!("calc({px}px + {percent}%)"),
            }
        }

        if name.starts_with("--") {
            return self
                .custom_properties
                .get(name)
                .cloned()
                .unwrap_or_default();
        }
        let Some(id) = PropertyId::from_name(name) else {
            return String::new();
        };
        match id {
            PropertyId::Display => self.display.to_string(),
            PropertyId::Position => self.position.to_string(),
            PropertyId::Visibility => self.visibility.to_string(),
            PropertyId::OverflowX => self.overflow.to_string(),
            PropertyId::OverflowY => self.overflow_y.to_string(),
            PropertyId::Float => self.float.to_string(),
            PropertyId::Clear => self.clear.to_string(),
            PropertyId::BoxSizing => self.box_sizing.to_string(),
            PropertyId::PointerEvents => self.pointer_events.to_string(),
            PropertyId::TextAlign => self.text_align.to_string(),
            PropertyId::WhiteSpace => self.white_space.to_string(),
            PropertyId::FontStyle => self.font_style.to_string(),
            PropertyId::TextDecorationLine => self.text_decoration_line.to_string(),
            PropertyId::TextTransform => self.text_transform.to_string(),
            PropertyId::Direction => self.direction.to_string(),
            PropertyId::WritingMode => self.writing_mode.to_string(),
            PropertyId::Color => self.color.to_css_string(),
            PropertyId::BackgroundColor => match self.background_color {
                crate::values::Color::Rgba(c) => c.to_css_string(),
                crate::values::Color::CurrentColor => self.color.to_css_string(),
            },
            PropertyId::Opacity => {
                if (self.opacity - 1.0).abs() < f32::EPSILON {
                    "1".into()
                } else {
                    format!("{}", self.opacity)
                }
            }
            PropertyId::FontSize => px(self.font_size),
            PropertyId::FontWeight => format!("{}", self.font_weight.0),
            PropertyId::FontFamily => self
                .font_family
                .iter()
                .map(crate::values::FontFamily::to_css)
                .collect::<Vec<_>>()
                .join(", "),
            PropertyId::ZIndex => match self.z_index {
                crate::values::ZIndex::Auto => "auto".into(),
                crate::values::ZIndex::Integer(i) => i.to_string(),
            },
            PropertyId::Width => lpa(self.width),
            PropertyId::Height => lpa(self.height),
            PropertyId::MinWidth => lp(self.min_width),
            PropertyId::MinHeight => lp(self.min_height),
            PropertyId::MaxWidth => max_size(self.max_width),
            PropertyId::MaxHeight => max_size(self.max_height),
            PropertyId::Top => lpa(self.top),
            PropertyId::Right => lpa(self.right),
            PropertyId::Bottom => lpa(self.bottom),
            PropertyId::Left => lpa(self.left),
            PropertyId::MarginTop => lpa(self.margin_top),
            PropertyId::MarginRight => lpa(self.margin_right),
            PropertyId::MarginBottom => lpa(self.margin_bottom),
            PropertyId::MarginLeft => lpa(self.margin_left),
            PropertyId::PaddingTop => lp(self.padding_top),
            PropertyId::PaddingRight => lp(self.padding_right),
            PropertyId::PaddingBottom => lp(self.padding_bottom),
            PropertyId::PaddingLeft => lp(self.padding_left),
            PropertyId::BorderTopWidth => px(self.border_top()),
            PropertyId::BorderRightWidth => px(self.border_right()),
            PropertyId::BorderBottomWidth => px(self.border_bottom()),
            PropertyId::BorderLeftWidth => px(self.border_left()),
            PropertyId::BorderTopStyle => self.border_top_style.to_string(),
            PropertyId::BorderRightStyle => self.border_right_style.to_string(),
            PropertyId::BorderBottomStyle => self.border_bottom_style.to_string(),
            PropertyId::BorderLeftStyle => self.border_left_style.to_string(),
            PropertyId::FlexDirection => self.flex_direction.to_string(),
            PropertyId::FlexWrap => self.flex_wrap.to_string(),
            PropertyId::JustifyContent => self.justify_content.to_string(),
            PropertyId::AlignItems => self.align_items.to_string(),
            PropertyId::FillRule => self.fill_rule.to_string(),
            PropertyId::StrokeLinecap => self.stroke_linecap.to_string(),
            PropertyId::StrokeLinejoin => self.stroke_linejoin.to_string(),
            PropertyId::StrokeMiterlimit => format!("{}", self.stroke_miterlimit),
            PropertyId::StrokeDashoffset => format!("{}", self.stroke_dashoffset),
            _ => String::new(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::stylesheet::parse_declaration_block;
    use crate::values::{FontWeight, LengthPercentageAuto};

    fn compute(parent: &ComputedStyle, css: &str, is_root: bool) -> ComputedStyle {
        let block = parse_declaration_block(css);
        let decls: Vec<&PropertyDeclaration> = block.declarations.iter().collect();
        let ctx = ComputeContext {
            parent,
            root_font_size: 16.0,
            viewport: Size::new(800.0, 600.0),
            is_root,
        };
        ComputedStyle::cascade(&decls, &ctx)
    }

    #[test]
    fn relative_units_and_inheritance() {
        let initial = ComputedStyle::initial();
        let parent = compute(
            &initial,
            "font-size: 20px; color: red; font-weight: bold",
            true,
        );
        assert_eq!(parent.font_size, 20.0);
        assert_eq!(parent.display, Display::Block, "root is blockified");

        let child = compute(
            &parent,
            "font-size: 1.5em; width: 2em; margin-left: 10%; font-weight: bolder",
            false,
        );
        assert_eq!(child.font_size, 30.0, "em on font-size uses the parent");
        assert_eq!(
            child.width,
            LengthPercentageAuto::Px(60.0),
            "em elsewhere uses own font-size"
        );
        assert_eq!(child.margin_left, LengthPercentageAuto::Percent(10.0));
        assert_eq!(child.color, Rgba::rgb(255, 0, 0), "color inherits");
        assert_eq!(child.font_weight, FontWeight(900), "bolder than bold");

        let reset = compute(
            &parent,
            "color: initial; font-size: unset; width: inherit",
            false,
        );
        assert_eq!(reset.color, Rgba::BLACK);
        assert_eq!(reset.font_size, 20.0);
        assert_eq!(reset.width, LengthPercentageAuto::Auto);

        let imaged = compute(
            &initial,
            "background-image: url(\"https://a.test/x.png\")",
            false,
        );
        assert_eq!(
            imaged.background_image,
            crate::values::BackgroundImage::Url("https://a.test/x.png".into())
        );
    }

    #[test]
    fn custom_properties_and_var_substitution() {
        let initial = ComputedStyle::initial();
        let parent = compute(&initial, "--brand: #00ff00; --gap: 4px", false);
        assert_eq!(parent.custom_property("--brand"), Some("#00ff00"));

        let child = compute(
            &parent,
            "color: var(--brand); padding-left: var(--missing, var(--gap)); width: var(--nope)",
            false,
        );
        assert_eq!(child.color, Rgba::rgb(0, 255, 0));
        assert_eq!(child.padding_left, crate::values::LengthPercentage::Px(4.0));
        assert_eq!(
            child.width,
            LengthPercentageAuto::Auto,
            "missing var without fallback -> unset"
        );

        let invalid = compute(&parent, "display: var(--gap)", false);
        assert_eq!(
            invalid.display,
            Display::Inline,
            "invalid at computed-value time -> initial"
        );
    }
}
