//! Computing a [`ComputedStyle`] from cascaded declarations.
//!
//! [`ComputedStyle`] itself is generated by the property table in
//! [`crate::properties`]; this module adds the cascade-application logic:
//! CSS-wide keywords, custom properties, `var()` substitution, the
//! `font-size`-first ordering that relative units depend on, and the
//! post-cascade fix-ups (blockification of positioned elements, root display).

use std::rc::Rc;

use ve_core::Size;

pub use crate::properties::{ComputedStyle, ConvertContext, CustomProperties};
use crate::properties::{PropertyId, SpecifiedValue};
use crate::stylesheet::PropertyDeclaration;
use crate::values::{BorderCollapse, Display, Float, Rgba};

/// Per-element facts the cascade needs that are not in the declarations.
#[derive(Clone, Copy, Debug)]
pub struct ComputeContext<'a> {
    /// The parent's computed style (or the initial style for the root).
    pub parent: &'a ComputedStyle,
    /// Root element font size in pixels (`rem`).
    pub root_font_size: f32,
    /// Viewport size in pixels (`vw`, `vh`).
    pub viewport: Size,
    /// Whether this is the root element.
    pub is_root: bool,
}

impl ComputedStyle {
    /// Applies `declarations`, already sorted so that the *last* one wins, on
    /// top of the style inherited from `ctx.parent`.
    #[must_use]
    pub fn cascade(declarations: &[&PropertyDeclaration], ctx: &ComputeContext<'_>) -> Self {
        let mut style = Self::inherited_from(ctx.parent);

        // 1. Custom properties first: `var()` in other properties reads them.
        for decl in declarations
            .iter()
            .filter(|d| matches!(d.property, PropertyId::Custom(_)))
        {
            style.apply_custom(decl, ctx.parent);
        }
        // 2. `font-size` next: `em`, `%` line-height etc. depend on it.
        let mut convert = style.convert_context(ctx);
        for decl in declarations
            .iter()
            .filter(|d| d.property == PropertyId::FontSize)
        {
            style.apply(decl, ctx.parent, &convert);
        }
        convert.font_size = style.font_size;
        // 3. Everything else in cascade order.
        for decl in declarations.iter().filter(|d| {
            d.property != PropertyId::FontSize && !matches!(d.property, PropertyId::Custom(_))
        }) {
            style.apply(decl, ctx.parent, &convert);
        }

        style.fix_up(ctx.is_root);
        style
    }

    fn convert_context(&self, ctx: &ComputeContext<'_>) -> ConvertContext {
        ConvertContext {
            font_size: self.font_size,
            parent_font_size: ctx.parent.font_size,
            parent_font_weight: ctx.parent.font_weight,
            parent_color: ctx.parent.color,
            root_font_size: ctx.root_font_size,
            viewport: ctx.viewport,
        }
    }

    fn apply_custom(&mut self, decl: &PropertyDeclaration, parent: &Self) {
        let PropertyId::Custom(name) = &decl.property else {
            return;
        };
        match &decl.value {
            SpecifiedValue::Raw(raw) => {
                let resolved = match substitute_var(raw, &self.custom_properties, 0) {
                    Some(r) => r,
                    None => return, // invalid at computed-value time -> guaranteed-invalid
                };
                Rc::make_mut(&mut self.custom_properties).insert(name.clone(), resolved);
            }
            SpecifiedValue::Initial => {
                Rc::make_mut(&mut self.custom_properties).remove(name);
            }
            SpecifiedValue::Inherit | SpecifiedValue::Unset | SpecifiedValue::Revert => {
                match parent.custom_properties.get(name) {
                    Some(v) => {
                        Rc::make_mut(&mut self.custom_properties).insert(name.clone(), v.clone());
                    }
                    None => {
                        Rc::make_mut(&mut self.custom_properties).remove(name);
                    }
                }
            }
            _ => {}
        }
    }

    /// Applies one declaration. Invalid values (after `var()` substitution)
    /// behave as `unset`, per the custom properties specification.
    fn apply(&mut self, decl: &PropertyDeclaration, parent: &Self, ctx: &ConvertContext) {
        let prop = &decl.property;
        match &decl.value {
            SpecifiedValue::Inherit => self.inherit_field(prop, parent),
            SpecifiedValue::Initial => self.reset_field(prop),
            SpecifiedValue::Unset | SpecifiedValue::Revert => self.unset_field(prop, parent),
            SpecifiedValue::Var(raw) => {
                let substituted = substitute_var(raw, &self.custom_properties, 0)
                    .and_then(|text| prop.parse_value_str(&text));
                match substituted {
                    Some(value) if value.is_css_wide() => {
                        let resolved = PropertyDeclaration {
                            property: prop.clone(),
                            value,
                            important: decl.important,
                        };
                        self.apply(&resolved, parent, ctx);
                    }
                    Some(value) => {
                        if !self.set_field(prop, &value, ctx) {
                            self.unset_field(prop, parent);
                        }
                    }
                    None => self.unset_field(prop, parent),
                }
            }
            value => {
                self.set_field(prop, value, ctx);
            }
        }
    }

    fn unset_field(&mut self, prop: &PropertyId, parent: &Self) {
        if prop.is_inherited() {
            self.inherit_field(prop, parent);
        } else {
            self.reset_field(prop);
        }
    }

    /// Post-cascade adjustments mandated by CSS Display / Positioning /
    /// Backgrounds: blockification of out-of-flow and floated boxes, the
    /// root's display, and border widths of sides whose style paints nothing.
    fn fix_up(&mut self, is_root: bool) {
        if self.position.is_out_of_flow() {
            // Absolutely positioned boxes do not float.
            self.float = Float::None;
        }
        if self.position.is_out_of_flow() || self.float != Float::None || is_root {
            self.display = self.display.blockified();
        }
        if is_root && self.display == Display::Contents {
            self.display = Display::Block;
        }
        if self.border_top_style.is_none() {
            self.border_top_width = 0.0;
        }
        if self.border_right_style.is_none() {
            self.border_right_width = 0.0;
        }
        if self.border_bottom_style.is_none() {
            self.border_bottom_width = 0.0;
        }
        if self.border_left_style.is_none() {
            self.border_left_width = 0.0;
        }
        if self.border_collapse == BorderCollapse::Collapse {
            self.border_spacing_x = 0.0;
            self.border_spacing_y = 0.0;
        }
    }

    /// Returns `true` if the two styles differ in a way that changes layout
    /// (anything except paint-only properties).
    #[must_use]
    pub fn layout_eq(&self, other: &Self) -> bool {
        let paint_only = |s: &Self| {
            (
                s.color,
                s.background_color,
                s.border_top_color,
                s.border_right_color,
                s.border_bottom_color,
                s.border_left_color,
                s.opacity,
                s.visibility,
                s.pointer_events,
                s.text_decoration_line,
            )
        };
        let mut a = self.clone();
        let mut b = other.clone();
        // Neutralise paint-only differences before comparing.
        if paint_only(&a) != paint_only(&b) {
            a.color = b.color;
            a.background_color = b.background_color;
            a.border_top_color = b.border_top_color;
            a.border_right_color = b.border_right_color;
            a.border_bottom_color = b.border_bottom_color;
            a.border_left_color = b.border_left_color;
            a.opacity = b.opacity;
            a.visibility = b.visibility;
            a.pointer_events = b.pointer_events;
            a.text_decoration_line = b.text_decoration_line;
        }
        b.custom_properties = a.custom_properties.clone();
        a == b
    }

    /// Returns `true` if the element generates a box (`display != none`).
    #[must_use]
    pub fn is_displayed(&self) -> bool {
        self.display != Display::None
    }

    /// The colour used for text and as `currentcolor` (alias of `color`).
    #[must_use]
    pub fn current_color(&self) -> Rgba {
        self.color
    }

    /// Looks up a custom property by `--name`.
    #[must_use]
    pub fn custom_property(&self, name: &str) -> Option<&str> {
        self.custom_properties.get(name).map(String::as_str)
    }
}

/// Textually substitutes every `var(--name[, fallback])` in `raw`. Returns
/// `None` if a reference has no value and no fallback (or recursion is too
/// deep), which makes the declaration invalid at computed-value time.
pub fn substitute_var(raw: &str, custom: &CustomProperties, depth: usize) -> Option<String> {
    if depth > 16 {
        return None;
    }
    let mut out = String::with_capacity(raw.len());
    let mut rest = raw;
    while let Some(pos) = rest.find("var(") {
        out.push_str(&rest[..pos]);
        let after = &rest[pos + 4..];
        let (inner, tail) = split_balanced(after)?;
        let (name, fallback) = match inner.find(',') {
            Some(c) => (inner[..c].trim(), Some(inner[c + 1..].trim())),
            None => (inner.trim(), None),
        };
        if !name.starts_with("--") {
            return None;
        }
        match custom.get(name) {
            Some(value) => out.push_str(value),
            None => out.push_str(&substitute_var(fallback?, custom, depth + 1)?),
        }
        rest = tail;
    }
    out.push_str(rest);
    Some(out)
}

/// Splits `text` at the parenthesis that closes an already-opened `(`.
/// Returns the content before it and the text after it.
fn split_balanced(text: &str) -> Option<(&str, &str)> {
    let mut depth = 1usize;
    for (i, ch) in text.char_indices() {
        match ch {
            '(' => depth += 1,
            ')' => {
                depth -= 1;
                if depth == 0 {
                    return Some((&text[..i], &text[i + 1..]));
                }
            }
            _ => {}
        }
    }
    None
}

impl ComputedStyle {
    /// Serialises a longhand (or custom property) as CSS text for
    /// `getComputedStyle`. Unknown names yield the empty string.
    #[must_use]
    pub fn property_css(&self, name: &str) -> String {
        use crate::values::{LengthPercentage, LengthPercentageAuto, LineHeight, MaxSize, VerticalAlign};

        fn px(v: f32) -> String {
            if v == 0.0 {
                "0px".into()
            } else {
                format!("{v}px")
            }
        }
        fn lp(v: LengthPercentage) -> String {
            match v {
                LengthPercentage::Px(v) => px(v),
                LengthPercentage::Percent(p) => format!("{p}%"),
                LengthPercentage::Calc { px, percent } => format!("calc({px}px + {percent}%)"),
            }
        }
        fn lpa(v: LengthPercentageAuto) -> String {
            match v {
                LengthPercentageAuto::Auto => "auto".into(),
                LengthPercentageAuto::Px(v) => px(v),
                LengthPercentageAuto::Percent(p) => format!("{p}%"),
                LengthPercentageAuto::Calc { px, percent } => format!("calc({px}px + {percent}%)"),
            }
        }
        fn max_size(v: MaxSize) -> String {
            match v {
                MaxSize::None => "none".into(),
                MaxSize::Px(v) => px(v),
                MaxSize::Percent(p) => format!("{p}%"),
                MaxSize::Calc { px, percent } => format!("calc({px}px + {percent}%)"),
            }
        }

        if name.starts_with("--") {
            return self
                .custom_properties
                .get(name)
                .cloned()
                .unwrap_or_default();
        }
        let Some(id) = PropertyId::from_name(name) else {
            return String::new();
        };
        match id {
            PropertyId::Display => self.display.to_string(),
            PropertyId::Position => self.position.to_string(),
            PropertyId::Visibility => self.visibility.to_string(),
            PropertyId::OverflowX => self.overflow.to_string(),
            PropertyId::OverflowY => self.overflow_y.to_string(),
            PropertyId::Float => self.float.to_string(),
            PropertyId::Clear => self.clear.to_string(),
            PropertyId::BoxSizing => self.box_sizing.to_string(),
            PropertyId::PointerEvents => self.pointer_events.to_string(),
            PropertyId::TextAlign => self.text_align.to_string(),
            PropertyId::WhiteSpace => self.white_space.to_string(),
            PropertyId::FontStyle => self.font_style.to_string(),
            PropertyId::TextDecorationLine => self.text_decoration_line.to_string(),
            PropertyId::TextTransform => self.text_transform.to_string(),
            PropertyId::Direction => self.direction.to_string(),
            PropertyId::WritingMode => self.writing_mode.to_string(),
            PropertyId::Color => self.color.to_css_string(),
            PropertyId::BackgroundColor => match self.background_color {
                crate::values::Color::Rgba(c) => c.to_css_string(),
                crate::values::Color::CurrentColor => self.color.to_css_string(),
            },
            PropertyId::Opacity => {
                if (self.opacity - 1.0).abs() < f32::EPSILON {
                    "1".into()
                } else {
                    format!("{}", self.opacity)
                }
            }
            PropertyId::FontSize => px(self.font_size),
            PropertyId::FontWeight => format!("{}", self.font_weight.0),
            PropertyId::FontFamily => self
                .font_family
                .iter()
                .map(crate::values::FontFamily::to_css)
                .collect::<Vec<_>>()
                .join(", "),
            PropertyId::ZIndex => match self.z_index {
                crate::values::ZIndex::Auto => "auto".into(),
                crate::values::ZIndex::Integer(i) => i.to_string(),
            },
            PropertyId::Width => lpa(self.width),
            PropertyId::Height => lpa(self.height),
            PropertyId::MinWidth => lp(self.min_width),
            PropertyId::MinHeight => lp(self.min_height),
            PropertyId::MaxWidth => max_size(self.max_width),
            PropertyId::MaxHeight => max_size(self.max_height),
            PropertyId::Top => lpa(self.top),
            PropertyId::Right => lpa(self.right),
            PropertyId::Bottom => lpa(self.bottom),
            PropertyId::Left => lpa(self.left),
            PropertyId::MarginTop => lpa(self.margin_top),
            PropertyId::MarginRight => lpa(self.margin_right),
            PropertyId::MarginBottom => lpa(self.margin_bottom),
            PropertyId::MarginLeft => lpa(self.margin_left),
            PropertyId::PaddingTop => lp(self.padding_top),
            PropertyId::PaddingRight => lp(self.padding_right),
            PropertyId::PaddingBottom => lp(self.padding_bottom),
            PropertyId::PaddingLeft => lp(self.padding_left),
            PropertyId::BorderTopWidth => px(self.border_top()),
            PropertyId::BorderRightWidth => px(self.border_right()),
            PropertyId::BorderBottomWidth => px(self.border_bottom()),
            PropertyId::BorderLeftWidth => px(self.border_left()),
            PropertyId::BorderTopStyle => self.border_top_style.to_string(),
            PropertyId::BorderRightStyle => self.border_right_style.to_string(),
            PropertyId::BorderBottomStyle => self.border_bottom_style.to_string(),
            PropertyId::BorderLeftStyle => self.border_left_style.to_string(),
            PropertyId::FlexDirection => self.flex_direction.to_string(),
            PropertyId::FlexWrap => self.flex_wrap.to_string(),
            PropertyId::JustifyContent => self.justify_content.to_string(),
            PropertyId::AlignItems => self.align_items.to_string(),
            PropertyId::FillRule => self.fill_rule.to_string(),
            PropertyId::StrokeLinecap => self.stroke_linecap.to_string(),
            PropertyId::StrokeLinejoin => self.stroke_linejoin.to_string(),
            PropertyId::StrokeMiterlimit => format!("{}", self.stroke_miterlimit),
            PropertyId::StrokeDashoffset => format!("{}", self.stroke_dashoffset),
            PropertyId::AccentColor => match self.accent_color {
                crate::values::Color::Rgba(c) => c.to_css_string(),
                crate::values::Color::CurrentColor => self.color.to_css_string(),
            },
            PropertyId::CaretColor => match self.caret_color {
                crate::values::Color::Rgba(c) => c.to_css_string(),
                crate::values::Color::CurrentColor => self.color.to_css_string(),
            },
            PropertyId::LetterSpacing => {
                if self.letter_spacing == 0.0 {
                    "normal".into()
                } else {
                    px(self.letter_spacing)
                }
            }
            PropertyId::WordSpacing => {
                if self.word_spacing == 0.0 {
                    "normal".into()
                } else {
                    px(self.word_spacing)
                }
            }
            PropertyId::LineHeight => match self.line_height {
                LineHeight::Normal => "normal".into(),
                LineHeight::Number(n) => format!("{n}"),
                LineHeight::Px(v) => px(v),
            },
            PropertyId::TabSize => format!("{}", self.tab_size),
            PropertyId::UserSelect => self.user_select.to_string(),
            PropertyId::Cursor => self.cursor.clone(),
            PropertyId::WillChange => self.will_change.clone(),
            PropertyId::OutlineWidth => px(self.outline_width),
            PropertyId::OutlineStyle => self.outline_style.to_string(),
            PropertyId::OutlineColor => match self.outline_color {
                crate::values::Color::Rgba(c) => c.to_css_string(),
                crate::values::Color::CurrentColor => self.color.to_css_string(),
            },
            PropertyId::OutlineOffset => px(self.outline_offset),
            PropertyId::BorderTopColor => match self.border_top_color {
                crate::values::Color::Rgba(c) => c.to_css_string(),
                crate::values::Color::CurrentColor => self.color.to_css_string(),
            },
            PropertyId::BorderRightColor => match self.border_right_color {
                crate::values::Color::Rgba(c) => c.to_css_string(),
                crate::values::Color::CurrentColor => self.color.to_css_string(),
            },
            PropertyId::BorderBottomColor => match self.border_bottom_color {
                crate::values::Color::Rgba(c) => c.to_css_string(),
                crate::values::Color::CurrentColor => self.color.to_css_string(),
            },
            PropertyId::BorderLeftColor => match self.border_left_color {
                crate::values::Color::Rgba(c) => c.to_css_string(),
                crate::values::Color::CurrentColor => self.color.to_css_string(),
            },
            PropertyId::VerticalAlign => match self.vertical_align {
                VerticalAlign::Baseline => "baseline".into(),
                VerticalAlign::Sub => "sub".into(),
                VerticalAlign::Super => "super".into(),
                VerticalAlign::Top => "top".into(),
                VerticalAlign::TextTop => "text-top".into(),
                VerticalAlign::Middle => "middle".into(),
                VerticalAlign::Bottom => "bottom".into(),
                VerticalAlign::TextBottom => "text-bottom".into(),
                VerticalAlign::Length(v) => px(v),
                VerticalAlign::Percent(p) => format!("{p}%"),
            },
            PropertyId::Hyphens => self.hyphens.to_string(),
            PropertyId::TextIndent => lp(self.text_indent),
            PropertyId::TextAlignLast => self.text_align_last.to_string(),
            PropertyId::WordBreak => self.word_break.to_string(),
            PropertyId::OverflowWrap => self.overflow_wrap.to_string(),
            PropertyId::ScrollBehavior => self.scroll_behavior.to_string(),
            PropertyId::OverscrollBehavior => self.overscroll_behavior.to_string(),
            PropertyId::Appearance => self.appearance.to_string(),
            PropertyId::Orphans => format!("{}", self.orphans),
            PropertyId::Widows => format!("{}", self.widows),
            PropertyId::AnimationTimingFunction => self.animation_timing_function.clone(),
            PropertyId::TextWrap => self.text_wrap.to_string(),
            PropertyId::FontVariant => self.font_variant.to_string(),
            PropertyId::TextOverflow => self.text_overflow.to_string(),
            PropertyId::UnicodeBidi => self.unicode_bidi.to_string(),
            PropertyId::ListStyleType => self.list_style_type.to_string(),
            PropertyId::ListStylePosition => self.list_style_position.to_string(),
            PropertyId::FlexGrow => format!("{}", self.flex_grow),
            PropertyId::FlexShrink => format!("{}", self.flex_shrink),
            PropertyId::FlexBasis => lpa(self.flex_basis),
            PropertyId::Order => format!("{}", self.order),
            PropertyId::AlignContent => self.align_content.to_string(),
            PropertyId::JustifyItems => self.justify_items.to_string(),
            PropertyId::AlignSelf => self.align_self.to_string(),
            PropertyId::JustifySelf => self.justify_self.to_string(),
            PropertyId::RowGap => lp(self.row_gap),
            PropertyId::ColumnGap => lp(self.column_gap),
            PropertyId::Isolation => self.isolation.to_string(),
            PropertyId::MixBlendMode => self.mix_blend_mode.to_string(),
            PropertyId::AnimationFillMode => self.animation_fill_mode.to_string(),
            PropertyId::AnimationPlayState => self.animation_play_state.to_string(),
            PropertyId::AnimationDirection => self.animation_direction.to_string(),
            PropertyId::AnimationName => {
                if self.animation_name.is_empty() {
                    "none".into()
                } else {
                    self.animation_name.clone()
                }
            }
            PropertyId::TransitionProperty => self.transition_property.clone(),
            PropertyId::TransitionTimingFunction => self.transition_timing_function.clone(),
            PropertyId::Contain => self.contain.to_string(),
            PropertyId::ScrollbarWidth => self.scrollbar_width.to_string(),
            PropertyId::ContainerType => self.container_type.to_string(),
            PropertyId::TouchAction => self.touch_action.to_string(),
            PropertyId::ImageRendering => self.image_rendering.to_string(),
            PropertyId::PreferredColorScheme => self.color_scheme.to_string(),
            PropertyId::ColumnSpan => self.column_span.to_string(),
            PropertyId::TableLayout => self.table_layout.to_string(),
            PropertyId::EmptyCells => self.empty_cells.to_string(),
            PropertyId::ContentVisibility => self.content_visibility.to_string(),
            PropertyId::FieldSizing => self.field_sizing.to_string(),
            PropertyId::Resize => self.resize.to_string(),
            PropertyId::TextOrientation => self.text_orientation.to_string(),
            PropertyId::BackgroundBlendMode => self.background_blend_mode.to_string(),
            PropertyId::FontStretch => self.font_stretch.to_string(),
            PropertyId::FontVariantLigatures => self.font_variant_ligatures.to_string(),
            PropertyId::FontVariantNumeric => self.font_variant_numeric.to_string(),
            PropertyId::FontKerning => self.font_kerning.to_string(),
            PropertyId::ScrollSnapType => self.scroll_snap_type.to_string(),
            PropertyId::ScrollSnapAlign => self.scroll_snap_align.to_string(),
            PropertyId::BreakBefore => self.break_before.to_string(),
            PropertyId::BreakAfter => self.break_after.to_string(),
            PropertyId::BreakInside => self.break_inside.to_string(),
            PropertyId::TextRendering => self.text_rendering.to_string(),
            PropertyId::FontSmoothing => self.font_smoothing.to_string(),
            PropertyId::TransformStyle => self.transform_style.to_string(),
            PropertyId::BackfaceVisibility => self.backface_visibility.to_string(),
            PropertyId::HangingPunctuation => self.hanging_punctuation.to_string(),
            PropertyId::TextEmphasis => self.text_emphasis.to_string(),
            PropertyId::BoxOrient => self.box_orient.to_string(),
            PropertyId::TransformBox => self.transform_box.to_string(),
            PropertyId::VectorEffect => self.vector_effect.to_string(),
            PropertyId::Speak => self.speak.to_string(),
            PropertyId::ForcedColorAdjust => self.forced_color_adjust.to_string(),
            PropertyId::TextJustify => self.text_justify.to_string(),
            PropertyId::PrintColorAdjust => self.print_color_adjust.to_string(),
            PropertyId::FontDisplay => self.font_display.to_string(),
            PropertyId::FontOpticalSizing => self.font_optical_sizing.to_string(),
            PropertyId::FontSynthesis => self.font_synthesis.to_string(),
            PropertyId::RubyPosition => self.ruby_position.to_string(),
            PropertyId::MathStyle => self.math_style.to_string(),
            PropertyId::OverflowScrolling => self.overflow_scrolling.to_string(),
            PropertyId::TouchCallout => self.touch_callout.to_string(),
            PropertyId::ColorInterpolationFilters => self.color_interpolation_filters.to_string(),
            PropertyId::FontVariantEastAsian => self.font_variant_east_asian.to_string(),
            PropertyId::MaskComposite => self.mask_composite.to_string(),
            PropertyId::ScrollSnapStop => self.scroll_snap_stop.to_string(),
            PropertyId::BorderCollapse => self.border_collapse.to_string(),
            PropertyId::CaptionSide => self.caption_side.to_string(),
            PropertyId::TextDecorationStyle => self.text_decoration_style.to_string(),
            PropertyId::TextUnderlinePosition => self.text_underline_position.to_string(),
            PropertyId::ColumnRuleStyle => self.column_rule_style.to_string(),
            PropertyId::ObjectFit => self.object_fit.to_string(),
            PropertyId::BackgroundRepeat => self.background_repeat.to_string(),
            PropertyId::BackgroundClip => self.background_clip.to_string(),
            PropertyId::BackgroundOrigin => self.background_origin.to_string(),
            PropertyId::BackgroundAttachment => self.background_attachment.to_string(),
            PropertyId::GridAutoFlow => self.grid_auto_flow.to_string(),
            PropertyId::Zoom => format!("{}", self.zoom),
            PropertyId::StrokeWidth => px(self.stroke_width),
            PropertyId::ScrollMargin => px(self.scroll_margin),
            PropertyId::ScrollPadding => px(self.scroll_padding),
            PropertyId::TextDecorationThickness => px(self.text_decoration_thickness),
            PropertyId::TextUnderlineOffset => px(self.text_underline_offset),
            PropertyId::ColumnRuleWidth => px(self.column_rule_width),
            PropertyId::MarkerOffset => px(self.marker_offset),
            PropertyId::MathDepth => format!("{}", self.math_depth),
            PropertyId::FontFeatureSettings => self.font_feature_settings.clone(),
            PropertyId::FontLanguageOverride => self.font_language_override.clone(),
            PropertyId::FontPalette => self.font_palette.clone(),
            PropertyId::AnimationRange => self.animation_range.clone(),
            PropertyId::AnimationTimeline => self.animation_timeline.clone(),
            PropertyId::ViewTimeline => self.view_timeline.clone(),
            PropertyId::BorderImageSlice => self.border_image_slice.clone(),
            PropertyId::TextDecorationColor => match self.text_decoration_color {
                crate::values::Color::Rgba(c) => c.to_css_string(),
                crate::values::Color::CurrentColor => self.color.to_css_string(),
            },
            PropertyId::ColumnRuleColor => match self.column_rule_color {
                crate::values::Color::Rgba(c) => c.to_css_string(),
                crate::values::Color::CurrentColor => self.color.to_css_string(),
            },
            PropertyId::Fill => match self.fill {
                crate::values::Color::Rgba(c) => c.to_css_string(),
                crate::values::Color::CurrentColor => self.color.to_css_string(),
            },
            PropertyId::Stroke => match self.stroke {
                crate::values::Color::Rgba(c) => c.to_css_string(),
                crate::values::Color::CurrentColor => self.color.to_css_string(),
            },
            _ => String::new(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::stylesheet::parse_declaration_block;
    use crate::values::{FontWeight, LengthPercentageAuto};

    fn compute(parent: &ComputedStyle, css: &str, is_root: bool) -> ComputedStyle {
        let block = parse_declaration_block(css);
        let decls: Vec<&PropertyDeclaration> = block.declarations.iter().collect();
        let ctx = ComputeContext {
            parent,
            root_font_size: 16.0,
            viewport: Size::new(800.0, 600.0),
            is_root,
        };
        ComputedStyle::cascade(&decls, &ctx)
    }

    #[test]
    fn relative_units_and_inheritance() {
        let initial = ComputedStyle::initial();
        let parent = compute(
            &initial,
            "font-size: 20px; color: red; font-weight: bold",
            true,
        );
        assert_eq!(parent.font_size, 20.0);
        assert_eq!(parent.display, Display::Block, "root is blockified");

        let child = compute(
            &parent,
            "font-size: 1.5em; width: 2em; margin-left: 10%; font-weight: bolder",
            false,
        );
        assert_eq!(child.font_size, 30.0, "em on font-size uses the parent");
        assert_eq!(
            child.width,
            LengthPercentageAuto::Px(60.0),
            "em elsewhere uses own font-size"
        );
        assert_eq!(child.margin_left, LengthPercentageAuto::Percent(10.0));
        assert_eq!(child.color, Rgba::rgb(255, 0, 0), "color inherits");
        assert_eq!(child.font_weight, FontWeight(900), "bolder than bold");

        let reset = compute(
            &parent,
            "color: initial; font-size: unset; width: inherit",
            false,
        );
        assert_eq!(reset.color, Rgba::BLACK);
        assert_eq!(reset.font_size, 20.0);
        assert_eq!(reset.width, LengthPercentageAuto::Auto);

        let imaged = compute(
            &initial,
            "background-image: url(\"https://a.test/x.png\")",
            false,
        );
        assert_eq!(
            imaged.background_image,
            crate::values::BackgroundImage::Url("https://a.test/x.png".into())
        );
    }

    #[test]
    fn custom_properties_and_var_substitution() {
        let initial = ComputedStyle::initial();
        let parent = compute(&initial, "--brand: #00ff00; --gap: 4px", false);
        assert_eq!(parent.custom_property("--brand"), Some("#00ff00"));

        let child = compute(
            &parent,
            "color: var(--brand); padding-left: var(--missing, var(--gap)); width: var(--nope)",
            false,
        );
        assert_eq!(child.color, Rgba::rgb(0, 255, 0));
        assert_eq!(child.padding_left, crate::values::LengthPercentage::Px(4.0));
        assert_eq!(
            child.width,
            LengthPercentageAuto::Auto,
            "missing var without fallback -> unset"
        );

        let invalid = compute(&parent, "display: var(--gap)", false);
        assert_eq!(
            invalid.display,
            Display::Inline,
            "invalid at computed-value time -> initial"
        );
    }

    #[test]
    fn property_css_exposes_spacing_and_ui() {
        let initial = ComputedStyle::initial();
        let style = compute(
            &initial,
            "letter-spacing: 4px; word-spacing: 8px; line-height: 2; tab-size: 4; \
             user-select: none; cursor: pointer; will-change: transform; \
             outline-width: 2px; outline-style: solid; outline-color: red; outline-offset: 1px; \
             border-top-color: blue; vertical-align: middle; hyphens: none; text-indent: 16px",
            false,
        );
        assert_eq!(style.property_css("letter-spacing"), "4px");
        assert_eq!(style.property_css("word-spacing"), "8px");
        assert_eq!(style.property_css("line-height"), "2");
        assert_eq!(style.property_css("tab-size"), "4");
        assert_eq!(style.property_css("user-select"), "none");
        assert_eq!(style.property_css("cursor"), "pointer");
        assert_eq!(style.property_css("will-change"), "transform");
        assert_eq!(style.property_css("outline-width"), "2px");
        assert_eq!(style.property_css("outline-style"), "solid");
        assert!(style.property_css("outline-color").contains("255, 0, 0"));
        assert_eq!(style.property_css("outline-offset"), "1px");
        assert!(style.property_css("border-top-color").contains("0, 0, 255"));
        assert_eq!(style.property_css("vertical-align"), "middle");
        assert_eq!(style.property_css("hyphens"), "none");
        assert_eq!(style.property_css("text-indent"), "16px");
        assert_eq!(ComputedStyle::initial().property_css("letter-spacing"), "normal");
        assert_eq!(ComputedStyle::initial().property_css("line-height"), "normal");
    }

    #[test]
    fn property_css_exposes_break_and_scroll_keywords() {
        let initial = ComputedStyle::initial();
        let style = compute(
            &initial,
            "text-align-last: center; word-break: break-all; overflow-wrap: anywhere; \
             scroll-behavior: smooth; overscroll-behavior: none; appearance: none; \
             orphans: 3; widows: 4; animation-timing-function: linear",
            false,
        );
        assert_eq!(style.property_css("text-align-last"), "center");
        assert_eq!(style.property_css("word-break"), "break-all");
        assert_eq!(style.property_css("overflow-wrap"), "anywhere");
        assert_eq!(style.property_css("scroll-behavior"), "smooth");
        assert_eq!(style.property_css("overscroll-behavior"), "none");
        assert_eq!(style.property_css("appearance"), "none");
        assert_eq!(style.property_css("orphans"), "3");
        assert_eq!(style.property_css("widows"), "4");
        assert_eq!(style.property_css("animation-timing-function"), "linear");
    }

    #[test]
    fn property_css_exposes_flex_list_and_paint_keywords() {
        let initial = ComputedStyle::initial();
        let style = compute(
            &initial,
            "flex-grow: 2; flex-shrink: 0; order: 3; list-style-type: decimal; \
             text-overflow: ellipsis; isolation: isolate; mix-blend-mode: multiply; \
             object-fit: cover; table-layout: fixed; empty-cells: hide; \
             content-visibility: hidden; resize: both; vector-effect: non-scaling-stroke; \
             fill: red; stroke: blue; stroke-width: 3px; zoom: 2",
            false,
        );
        assert_eq!(style.property_css("flex-grow"), "2");
        assert_eq!(style.property_css("flex-shrink"), "0");
        assert_eq!(style.property_css("order"), "3");
        assert_eq!(style.property_css("list-style-type"), "decimal");
        assert_eq!(style.property_css("text-overflow"), "ellipsis");
        assert_eq!(style.property_css("isolation"), "isolate");
        assert_eq!(style.property_css("mix-blend-mode"), "multiply");
        assert_eq!(style.property_css("object-fit"), "cover");
        assert_eq!(style.property_css("table-layout"), "fixed");
        assert_eq!(style.property_css("empty-cells"), "hide");
        assert_eq!(style.property_css("content-visibility"), "hidden");
        assert_eq!(style.property_css("resize"), "both");
        assert_eq!(style.property_css("vector-effect"), "non-scaling-stroke");
        assert!(style.property_css("fill").contains("255, 0, 0"));
        assert!(style.property_css("stroke").contains("0, 0, 255"));
        assert_eq!(style.property_css("stroke-width"), "3px");
        assert_eq!(style.property_css("zoom"), "2");
    }
}
